name = 'Theme name'
license = 'MIT'
licenselink = 'https://github.com/thegamershollow/When-Pigs-Fly/LICENSE'
description = 'Theme description'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/thegamershollow/When-Pigs-Fly'

# Taxonomy terms
tags = ['blog', 'wordpress', 'custom']


[author]
  name = 'TheGamersHollow'
  homepage = 'http://thegamershollow.space/'

